require('shared.treesitter').load()
require('shared.autocmd')
require('shared.commands')
require('shared.big_files').load()
require('shared.maps').load()
require('shared.configs')
require('config.lib_image').setup()
-- require('debugger').setup()
