" Generated by vim-plug
" 28-Jan-25 8:01:24 PM
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['CamelCaseMotion'].commit = 'de439d7c06cffd0839a29045a103fe4b44b15cdc'
silent! let g:plugs['Repeatable.vim'].commit = 'ab536625ef25e423514105dd790cb8a8450ec88b'
silent! let g:plugs['context.vim'].commit = '82eb26de265292808917b82f3eda2725b53d785c'
silent! let g:plugs['ctrlsf.vim'].commit = '32236a8b376d9311dec9b5fe795ca99d32060b13'
silent! let g:plugs['fzf'].commit = 'cf2bb5e40ea68f3b41cc76a012266b134c59c5bf'
silent! let g:plugs['fzf.vim'].commit = '556f45e79ae5e3970054fee4c4373472604a1b4e'
silent! let g:plugs['onehalf'].commit = '75eb2e97acd74660779fed8380989ee7891eec56'
silent! let g:plugs['undotree'].commit = '2556c6800b210b2096b55b66e74b4cc1d9ebbe4f'
silent! let g:plugs['vim-ReplaceWithRegister'].commit = 'b82bf59e5387b57d0125afb94fd7984061031136'
silent! let g:plugs['vim-airline'].commit = '7a552f415c48aed33bf7eaa3c50e78504d417913'
silent! let g:plugs['vim-asterisk'].commit = '77e97061d6691637a034258cc415d98670698459'
silent! let g:plugs['vim-buffet'].commit = '3ee5c836cd7ded3526902122e06110cd3f8549cb'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-context-commentstring'].commit = 'edcf56c323071ddabf3cf68c8d39edc22b930809'
silent! let g:plugs['vim-cursorword'].commit = '371fdd7fa8817c28aa09d181cfcfa3c7ca29bf56'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-flog'].commit = '74e52ba4de25eb5f03824d65087750636d795641'
silent! let g:plugs['vim-fugitive'].commit = 'd74a7cff4cfcf84f83cc7eccfa365488f3bbabc2'
silent! let g:plugs['vim-gitgutter'].commit = 'f06e1a9f1ca44aef8147ed7871c43a2951cb1107'
silent! let g:plugs['vim-repeat'].commit = '65846025c15494983dafe5e3b46c8f88ab2e9635'
silent! let g:plugs['vim-rhubarb'].commit = '386daa2e9d98e23e27ad089afcbe5c5a903e488d'
silent! let g:plugs['vim-smoothie'].commit = 'df1e324e9f3395c630c1c523d0555a01d2eb1b7e'
silent! let g:plugs['vim-suda'].commit = '9adda7d195222d4e2854efb2a88005a120296c47'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-system-copy'].commit = '00794585f8d91d811056a4165521baf55308505c'
silent! let g:plugs['vim-vinegar'].commit = 'bb1bcddf43cfebe05eb565a84ab069b357d0b3d6'
silent! let g:plugs['vim-visual-multi'].commit = 'a6975e7c1ee157615bbc80fc25e4392f71c344d4'

PlugUpdate!

