#!/usr/bin/env bash

[[ -v debug ]] && set -x

if [ "$OS" = 'Windows_NT' ]; then
  platform='windows'
  ext='zip'
  mpls='mpls.exe'
else
  platform="$(uname | tr '[:upper:]' '[:lower:]')"
  ext='tar.gz'
  mpls='mpls'
fi

if [ "$(uname -m)" = 'x86_64' ]; then
  architecture='amd64'
else
  architecture='arm64'
fi

string_url="$(curl -sL 'https://api.github.com/repos/mhersson/mpls/releases/latest' |
  grep "browser_download_url.*${platform}_${architecture}.*" |
  cut -d : -f 2,3 |
  tr -d \" | tr -d ' ')"

if [ -z "$string_url" ]; then
  exit 1
fi

download_file="mpld_download.$ext"
download_path="/tmp/$download_file"
extract_dir='/tmp/mpls_extracted'

# It will always override unless you use `--no-clobber` flag
curl -sL "$string_url" -o "$download_path"

mkdir -p "$extract_dir"
if [ "$OS" = 'Windows_NT' ]; then
  unzip "$download_path" -d "$extract_dir"
else
  tar -xzf "$download_path" -C "$extract_dir"
fi
chmod +x "$download_path/$mpls"

mv "$extract_dir/$mpls" "$HOME/.local/bin/$mpls"

